### PR TITLE
no independent description and content order

### PR DESCRIPTION
**Pull request by mosasiru**
issue: https://github.com/kurtmckee/feedparser/issues/59

no independent order of summary and content.

### CODE REVIEW

**Comment by cristoper** [comment]
This is a simple fix to an annoying bug. Any reason it hasn't been merged yet?

If it helps, I added a test case to @mosasiru's branch [1].

(It looks like this issue (#59) is a regression introduced way back with b06df763a0465ffd9acf7b3aae7ba3104234e6d3)

1: https://github.com/cristoper/feedparser/blob/95ae1d68d90bd01359a47afab23203a421e851a9/tests/wellformed/atom10/entry_content_and_summary.xml

**Comment by mosasiru** [comment]
thank you for PR. merged.

**Comment by mosasiru** [comment]
please reply it

**Comment by mosasiru** [comment]
Oh,  I wanted @kurtmckee to reply this pull-request. 
@cristoper You need not do anything more,  thank you very much for your supplement.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Two questions from me

1. Can you explain a bit more what your PR does? I do not understand. Maybe use some examples would improve my understanding. ;)
2. The PR is quite old. Kurt is stil on that project but lack of ressources. Do you (or anyone else) still need this PR need to be merged or not?

**Comment by cristoper** [comment]
This PR fixes a bug which incorrectly populates the entry description if the <description> or <summary> comes after the <content> tag in the feed. Issue #59 has an example, and [this simple test case](https://github.com/kurtmckee/feedparser/pull/60/commits/af7f9d3825f8d39c68f086f5aa1144363cf87ae5) fails without this PR.

I am still depending on @mosasiru 's fork with this PR applied for one of my projects, so it would be great if you could get this merged into the kurmckee repo.

Thank you.

**Comment by kurtmckee** [comment]
This is merged from #260.

**Pull request closed without merging**
