### PR TITLE
No longer test py32 or py33, py36 added

### PR DESCRIPTION
**Pull request by adamn**

### CODE REVIEW

**Comment by anarcat** [comment]
this conflicts with #93, can you guys agree on what is best?

**Comment by brettcannon** [comment]
If you're willing to drop Python 3.2 and 3.3 support then this one, if not then the other one.

**Comment by hugovk** [comment]
This one, 3.2 and 3.3 are both EOL. 

https://en.wikipedia.org/wiki/CPython#Version_history

**Comment by hugovk** [comment]
@adamn Don't forget to update setup.py.
https://github.com/kurtmckee/feedparser/blob/develop/setup.py#L29-L32

**Pull request merged**
