### PR TITLE
add ssl context argument to parse()

### PR DESCRIPTION
**Pull request by Dobatymo**
This allows to provide a custom SSL context. For example to add custom certificates (in a enterprise environment).

I made sure that the list of handlers created by `build_opener` didn't change by adding the HTTPS handler manually. This code will only work if the Python `ssl` module from the standard library is available. But I am not sure in which situation it would not be...

It would also solve this old issue https://github.com/kurtmckee/feedparser/issues/84

### CODE REVIEW

**Comment by NotSqrt** [comment]
Yes, please !
This would be very useful to solve a few certificates problems due to the Let's encrypt certificate chain !

**Comment by NotSqrt** [comment]
In the mean time, it's possible to provide a cert file with environment variable `SSL_CERT_FILE`.

**Comment by brunoamaral** [comment]
This would also be useful to me, any idea if it will be implemented ?

**Comment by kurtmckee** [comment]
No, I don't intend to add this. I want feedparser to get out of the HTTP client game entirely and push that to client libraries like requests. I don't want to add HTTP-related arguments to `parse()`.

**Comment by brunoamaral** [comment]
That's a solid argument, thank you for responding @kurtmckee. 

In your opinion, what would be the best way to handle the ssl then?

[I have no idea if the way I did it is sane](https://github.com/brunoamaral/gregory/pull/86/files).

**Comment by kurtmckee** [comment]
You could potentially use the requests package to get the URL and turn off SSL verification:

```python
requests.get('https://domain.example', verify=False)
#                                      ^^^^^^^^^^^^
```

The text in the response object can be passed into feedparser directly.

**Pull request closed without merging**
