### PR TITLE
Simple feed streaming

### PR DESCRIPTION
**Pull request by cscanlin**
This PR provides a simple API to continuously stream newly added entries from the given feed. Inspired by [tweepy](https://github.com/tweepy/tweepy/blob/master/tweepy/streaming.py#L190) and [praw](https://github.com/praw-dev/praw/blob/master/praw/models/util.py#L80) which both support similar functionality.

It's still fairly rough, and extremely simple, but I think with a little polish it can provide a nice addition to functionality with very little upkeep cost. The functionality is very simple:

1. Call feedparser.parse on input
2. yield each entry not already seen, and add to seen
    - a tag with unique data for each entry can be specified (default is 'id')
3. sleep for a specified amount of time (default is 30 seconds)
    - adding threading may boost performance because sleep is blocking

This repeats until the user breaks the loop. Called like this:

```
import feedparser

for entry in feedparser.stream_entries('https://www.reddit.com/r/programming/new.rss'):
    print(entry)
```

### CODE REVIEW

**Comment by anarcat** [comment]
what's the use case for this? can we have unit tests?

**Comment by int3l** [comment]
The **seen_ids** can become a memory problem, since it is never reset.
Maybe a limited [collections.deque](https://docs.python.org/2/library/collections.html#collections.deque) is a better suited solution?

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I do not see an advantage of this.
What is done here is not the job of a library like feedparser.
It should be done on application level.

Two big contras

1. It also ignores the ressource-efficient possibility of using [ETag or Modified Header](https://pythonhosted.org/feedparser/http-etag.html).
1. It ignores the hugh amount of problems and inconsistence implementations of ETag, Modified Headers on server side.

If you would test your code agains some 1.000 of the RSS feeds in my "laboratory" you would see what I mean.

I strongly recommand to drop this PR at this point.
Secondly I recommand @cscanlin to open an Issue and discuss her/his needs there and see if there is a solution on feedparsers side. If not I also would assisst with my expertise on using feedparser ressource-efficient and handling creepy servers and RSS-generators.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I vote for close.

**Comment by kurtmckee** [comment]
Chris, I appreciate your work on this. I apologize for not responding sooner.

Similar ideas have been suggested in several forms by various feed aggregator authors over the years, including

* Tell feedparser which GUID is the latest and have feedparser stop parsing if it sees that already-known GUID.
* Tell feedparser when the feed was last checked and have feedparser stop parsing if it sees a post that is older than the specified date.

On low-memory devices this could be helpful. However, the transport medium, HTTP, already has well-known mechanisms for such things: ETag and Last-Modified. These aren't perfect, since even a single new post will result in parsing the entire feed again just to get the single new post. However, nothing is perfect when simply downloading a document from a web server. Only a full API offered by the software running on the web server can offer perfection in this regard.

I'm closing this PR because I think that feedparser should be focused on parsing feeds excellently. Other features, like filtering the content in any way, should be done at a different application layer and outside of feedparser itself.

**Comment by anarcat** [comment]
> I'm closing this PR because I think that feedparser should be focused on parsing feeds excellently. Other features, like filtering the content in any way, should be done at a different application layer and outside of feedparser itself.

In [feed2exec](https://feed2exec.readthedocs.io/), I did this with [requests](https://github.com/psf/requests) and [cachecontrol](https://github.com/ionrock/cachecontrol). It generally works well, although some feeds don't send the right headers and are re-downloaded every time.

I do agree the feed fetching part of feedparser is somewhat superfluous: it's one of the first thing i hacked out. :) But it's useful for a quick start...

**Pull request closed without merging**
