### PR TITLE
Support for network request timeout

### PR DESCRIPTION
**Pull request by Lol4t0**
Default HTTP timeout is infinite. So feed can block request forever.
Specifying timeout allows to control execution flow.

### CODE REVIEW

**Comment by kisiel** [comment]
It's ok, I would merge.

**Comment by adamn** [comment]
This would be great to get integrated

**Comment by logandhead** [comment]
Please merge this in!!!!! Getting this integrated would be amazing.

**Comment by kurtmckee** [comment]
I don't intend to add any more networking code to feedparser. There are other more powerful libraries, like requests, that should be used instead for managing timeouts, authentication, and so forth.

**Pull request closed without merging**
