### PR TITLE
Adding support for dcterms:valid

### PR DESCRIPTION
**Pull request by sebest**
Hello,

I added support for dcterms:valid as described here: http://www.rssboard.org/media-rss

regards

### CODE REVIEW

**Comment by kurtmckee** [comment]
Looks good so far. Couple of notes attached and I think this will be ready for inclusion!

**Comment by kurtmckee** [comment]
Note to self: closes issue 380 on google code.

**Comment by sebest** [comment]
Hi Kurt,
Not sure that i will be able to apply these modifications as i don't work on this anymore: the pull request was almost 2 years ago :/
Sorry about that.

**Comment by kurtmckee** [comment]
Oof, you're right! No problem at all. Fixed up and merged into develop branch. Great work, Sebastien!

**Pull request closed without merging**
