### PR TITLE
GitHub Action to lint and test Python code

### PR DESCRIPTION
**Pull request by cclauss**
Output: https://github.com/cclauss/feedparser/actions

### CODE REVIEW

**Comment by int3l** [comment]
Consider using the [pre-commit](https://pre-commit.com/) framework for that. It is a lot more powerful and extensible than just a simpler linter. And the best part is that it can be integrated in your git workflow with hooks.

**Comment by cclauss** [comment]
@int3l Yes but it does nothing unless each contributor has pre-commit installed and properly configured.  A GitHub Actions can be created that runs the pre-commit tests even on pull requests from contributors that do not pre-commit installed and properly configured.  https://github.com/cclauss/itinerant-tester/blob/master/.github/workflows/pre-commit.yml

**Comment by int3l** [comment]
Yep, you can use pre-commit locally as well as in a CI environment - very flexible and convenient approach. All you need is a simple configuration file. And after the pre-commit run, you can use a second stage with the test runner itself.

**Comment by cclauss** [comment]
Something like https://github.com/cclauss/itinerant-tester/blob/master/.pre-commit-config.yaml ?

**Comment by int3l** [comment]
Yes, or one of these: [pyupgrade pre-commit config](https://github.com/asottile/pyupgrade/blob/master/.pre-commit-config.yaml); [pre-commit's own config](https://github.com/pre-commit/pre-commit/blob/master/.pre-commit-config.yaml), or even the [pytest pre-commit config](https://github.com/pytest-dev/pytest/blob/master/.pre-commit-config.yaml). Lots of options :)

**Comment by cclauss** [comment]
Closing in favor of @int3l 's PR.

**Comment by cclauss** [comment]
@int3l were you creating a PR for this?

**Comment by int3l** [comment]
@cclauss  Sorry for the confusion, I don't have a PR for this. I just commented on the possibility of using pre-commit.

**Pull request closed without merging**
