### PR TITLE
Travis CI: The matrix and sudo tags are deprecated

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by kurtmckee** [comment]
Thanks for this patch! I'm still not clear how this is helpful to feedparser. Is there something I should be setting up in the GitHub interface to enable this?

**Comment by cclauss** [comment]
Yes.  You can turn on Travis by logging into https://travis-ci.com/kurtmckee/feedparser via your GitHub credentials and then enabling the repo.  These tests should the autorun on all pushes to the repo.

**Comment by kurtmckee** [comment]
Christian, thanks so much for sharing these instructions! I'm really grateful!

**Comment by cclauss** [comment]
Kurt, Congratulations on v6!

Given that Travis is not running, should I submit a pull request for a GitHub Action instead?  They run without pre-configuration.

**Comment by kurtmckee** [comment]
Thanks so much! It's been a long time coming!

Yes, I would prefer to use GitHub Actions. Thanks so much!

**Comment by kurtmckee** [comment]
I've added support for GitHub Actions and removed the Travis CI file.

**Pull request merged**
