### PR TITLE
Add default timeout of 30s to requests

### LINKED ISSUE #76: Feedparser seems to occasionally hang and has no timeout
According to this the default timeout in urllib2 is -1, or None. So... this is a problem for long running programs, when occasionally some connection will hang everything.

Solution is pretty simple, add a timeout to the 'open' here https://github.com/kurtmckee/feedparser/blob/39a7157ff8280991d71af0d79e6412f66cffd470/feedparser/http.py#L175

I'll fork and try make a fix

### PR DESCRIPTION
**Pull request by peterashwell**
This fixes issue where urllib open has no default
timeout and can hang long running processes forever

Fixes #76

### CODE REVIEW

**Comment by kisiel** [comment]
:+1:

**Comment by JPFrancoia** [comment]
Please see PR https://github.com/kurtmckee/feedparser/pull/80.

**Comment by peterashwell** [comment]
Closing this in favor of #80

**Comment by mayureshw** [comment]
In the latest tagged release 6.0.10 I was not able to see the timeout parameter to parse.

I am facing the issue of parser hanging, that requires use of the timeout. What is the latest status on this - given above issue is very old now.

**Comment by kurtmckee** [comment]
Please use an HTTP client package like `requests`.

**Pull request closed without merging**
